export interface Product {
  id: string
  name: string
  slug: string
  brand: string
  price: number
  retailPrice?: number
  category: string
  subcategory?: string
  images: string[]
  badge?: 'new' | 'sale' | 'limited' | 'coming-soon' | 'out-of-stock'
  inStock: boolean
  stock?: number
  description: string
  specs?: Record<string, string>
  included?: string[]
  warranty?: string
  sku: string
  rating?: number
  reviewCount?: number
}

export interface Category {
  id: string
  name: string
  slug: string
  path: string
  subcategories?: SubCategory[]
}

export interface SubCategory {
  id: string
  name: string
  slug: string
  path: string
}

export interface PromoBanner {
  id: string
  title: string
  description: string
  image: string
  validUntil?: string
  ctaText: string
  ctaLink: string
}

export interface FeaturedCollection {
  id: string
  name: string
  slug: string
  productIds: string[]
}

// Categories
export const categories: Category[] = [
  {
    id: 'woodwinds',
    name: 'Woodwinds',
    slug: 'woodwinds',
    path: '/shop/woodwinds',
    subcategories: [
      { id: 'flutes', name: 'Flutes', slug: 'flutes', path: '/shop/woodwinds/flutes' },
      { id: 'clarinets', name: 'Clarinets', slug: 'clarinets', path: '/shop/woodwinds/clarinets' },
      { id: 'saxophones', name: 'Saxophones', slug: 'saxophones', path: '/shop/woodwinds/saxophones' },
      { id: 'mouthpieces-ligs', name: 'Mouthpieces & Ligatures', slug: 'mouthpieces-ligs', path: '/shop/woodwinds/mouthpieces-ligs' },
      { id: 'accessories', name: 'Accessories', slug: 'accessories', path: '/shop/woodwinds/accessories' },
      { id: 'sax-necks', name: 'Sax Necks', slug: 'sax-necks', path: '/shop/woodwinds/sax-necks' },
    ],
  },
  {
    id: 'brasswinds',
    name: 'Brasswinds',
    slug: 'brasswinds',
    path: '/shop/brasswinds',
    subcategories: [
      { id: 'trumpets', name: 'Trumpets', slug: 'trumpets', path: '/shop/brasswinds/trumpets' },
      { id: 'french-horns', name: 'French Horns', slug: 'french-horns', path: '/shop/brasswinds/french-horns' },
      { id: 'trombones', name: 'Trombones', slug: 'trombones', path: '/shop/brasswinds/trombones' },
      { id: 'euphoniums', name: 'Euphoniums', slug: 'euphoniums', path: '/shop/brasswinds/euphoniums' },
      { id: 'flugel-horns', name: 'Flugel Horns', slug: 'flugel-horns', path: '/shop/brasswinds/flugel-horns' },
      { id: 'yamaha-silent-brass', name: 'Yamaha Silent Brass', slug: 'yamaha-silent-brass', path: '/shop/brasswinds/yamaha-silent-brass' },
    ],
  },
  {
    id: 'percussion',
    name: 'Percussion Kit',
    slug: 'percussion',
    path: '/shop/percussion',
  },
  {
    id: 'strings',
    name: 'Strings',
    slug: 'strings',
    path: '/shop/strings',
  },
]

// Products (40+ products)
export const products: Product[] = [
  // Saxophones
  {
    id: '1',
    name: 'Yamaha YAS-280 Alto Saxophone',
    slug: 'yamaha-yas-280-alto-saxophone',
    brand: 'Yamaha',
    price: 1249.00,
    retailPrice: 1599.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YAS-280'],
    badge: 'sale',
    inStock: true,
    stock: 5,
    description: 'The Yamaha YAS-280 is a professional-grade alto saxophone perfect for students and intermediate players. Features hand-hammered bell for rich, resonant tone and professional keywork for smooth, responsive action.',
    specs: {
      'Key': 'Eb',
      'Body Material': 'Brass',
      'Finish': 'Gold Lacquer',
      'Weight': '2.4 kg',
    },
    included: ['Yamaha YAS-280 Alto Saxophone', 'Mouthpiece', 'Case', 'Neck Strap'],
    warranty: '5 years manufacturer warranty',
    sku: 'YAS-280-GL',
    rating: 4.8,
    reviewCount: 123,
  },
  {
    id: '2',
    name: 'Selmer Paris Reference 54 Alto Saxophone',
    slug: 'selmer-paris-reference-54-alto-saxophone',
    brand: 'Selmer Paris',
    price: 5499.00,
    retailPrice: 6499.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Selmer+Reference+54'],
    badge: 'new',
    inStock: true,
    stock: 2,
    description: 'The Reference 54 represents the pinnacle of Selmer craftsmanship. Designed for professional performers, this instrument delivers exceptional tone quality and playability.',
    specs: {
      'Key': 'Eb',
      'Body Material': 'Brass',
      'Finish': 'Gold Lacquer',
      'Weight': '2.5 kg',
    },
    included: ['Selmer Reference 54 Alto Saxophone', 'Professional Case', 'Mouthpiece'],
    warranty: 'Lifetime warranty',
    sku: 'REF54-ALTO',
    rating: 4.9,
    reviewCount: 45,
  },
  {
    id: '3',
    name: 'Yanagisawa AWO1 Alto Saxophone',
    slug: 'yanagisawa-awo1-alto-saxophone',
    brand: 'Yanagisawa',
    price: 3299.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yanagisawa+AWO1'],
    badge: 'limited',
    inStock: true,
    stock: 1,
    description: 'Handcrafted in Japan, the Yanagisawa AWO1 offers exceptional quality and tone. Perfect for serious students and professionals.',
    specs: {
      'Key': 'Eb',
      'Body Material': 'Brass',
      'Finish': 'Gold Lacquer',
    },
    included: ['Yanagisawa AWO1 Alto Saxophone', 'Case'],
    sku: 'AWO1-ALTO',
    rating: 4.7,
    reviewCount: 89,
  },
  {
    id: '4',
    name: 'Yamaha YTS-280 Tenor Saxophone',
    slug: 'yamaha-yts-280-tenor-saxophone',
    brand: 'Yamaha',
    price: 1499.00,
    retailPrice: 1899.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YTS-280'],
    badge: 'sale',
    inStock: true,
    stock: 8,
    description: 'Professional tenor saxophone with excellent intonation and response. Ideal for students advancing to intermediate level.',
    specs: {
      'Key': 'Bb',
      'Body Material': 'Brass',
      'Finish': 'Gold Lacquer',
    },
    included: ['Yamaha YTS-280 Tenor Saxophone', 'Case', 'Mouthpiece'],
    sku: 'YTS-280-TENOR',
    rating: 4.6,
    reviewCount: 156,
  },
  {
    id: '5',
    name: 'Selmer Paris Reference 36 Tenor Saxophone',
    slug: 'selmer-paris-reference-36-tenor-saxophone',
    brand: 'Selmer Paris',
    price: 5999.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Selmer+Reference+36'],
    badge: 'new',
    inStock: true,
    stock: 1,
    description: 'Professional tenor saxophone with rich, warm tone. Handcrafted in France.',
    specs: {
      'Key': 'Bb',
      'Body Material': 'Brass',
      'Finish': 'Gold Lacquer',
    },
    included: ['Selmer Reference 36 Tenor Saxophone', 'Professional Case'],
    sku: 'REF36-TENOR',
    rating: 5.0,
    reviewCount: 12,
  },
  // Clarinets
  {
    id: '6',
    name: 'Buffet Crampon R13 Bb Clarinet',
    slug: 'buffet-crampon-r13-bb-clarinet',
    brand: 'Buffet Crampon',
    price: 3499.00,
    retailPrice: 3999.00,
    category: 'woodwinds',
    subcategory: 'clarinets',
    images: ['https://via.placeholder.com/800x800?text=Buffet+R13'],
    badge: 'sale',
    inStock: true,
    stock: 4,
    description: 'The legendary R13 is the most popular professional clarinet in the world. Known for its rich, warm tone and excellent projection.',
    specs: {
      'Key': 'Bb',
      'Body Material': 'Grenadilla Wood',
      'Finish': 'Natural',
    },
    included: ['Buffet R13 Clarinet', 'Case', 'Mouthpiece'],
    sku: 'R13-BB',
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: '7',
    name: 'Yamaha YCL-650 Bb Clarinet',
    slug: 'yamaha-ycl-650-bb-clarinet',
    brand: 'Yamaha',
    price: 1899.00,
    category: 'woodwinds',
    subcategory: 'clarinets',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YCL-650'],
    badge: 'new',
    inStock: true,
    stock: 6,
    description: 'Intermediate clarinet with professional features. Excellent intonation and response.',
    specs: {
      'Key': 'Bb',
      'Body Material': 'Grenadilla Wood',
    },
    included: ['Yamaha YCL-650 Clarinet', 'Case'],
    sku: 'YCL-650',
    rating: 4.7,
    reviewCount: 98,
  },
  // Flutes
  {
    id: '8',
    name: 'Yamaha YFL-677H Professional Flute',
    slug: 'yamaha-yfl-677h-professional-flute',
    brand: 'Yamaha',
    price: 4299.00,
    category: 'woodwinds',
    subcategory: 'flutes',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YFL-677H'],
    badge: 'new',
    inStock: true,
    stock: 3,
    description: 'Professional flute with sterling silver headjoint and body. Exceptional tone and projection.',
    specs: {
      'Key': 'C',
      'Headjoint': 'Sterling Silver',
      'Body': 'Sterling Silver',
    },
    included: ['Yamaha YFL-677H Flute', 'Case'],
    sku: 'YFL-677H',
    rating: 4.8,
    reviewCount: 67,
  },
  {
    id: '9',
    name: 'Pearl PF-665 Flute',
    slug: 'pearl-pf-665-flute',
    brand: 'Pearl',
    price: 2499.00,
    category: 'woodwinds',
    subcategory: 'flutes',
    images: ['https://via.placeholder.com/800x800?text=Pearl+PF-665'],
    inStock: true,
    stock: 5,
    description: 'Intermediate flute with silver-plated headjoint. Great value for advancing students.',
    specs: {
      'Key': 'C',
      'Headjoint': 'Silver Plated',
    },
    included: ['Pearl PF-665 Flute', 'Case'],
    sku: 'PF-665',
    rating: 4.6,
    reviewCount: 45,
  },
  // Trumpets
  {
    id: '10',
    name: 'Bach Stradivarius Bb Trumpet',
    slug: 'bach-stradivarius-bb-trumpet',
    brand: 'Bach',
    price: 3499.00,
    retailPrice: 3999.00,
    category: 'brasswinds',
    subcategory: 'trumpets',
    images: ['https://via.placeholder.com/800x800?text=Bach+Stradivarius'],
    badge: 'sale',
    inStock: true,
    stock: 7,
    description: 'The legendary Bach Stradivarius trumpet. Professional standard for over 50 years.',
    specs: {
      'Key': 'Bb',
      'Bell': '4-3/4"',
      'Bore': 'ML',
    },
    included: ['Bach Stradivarius Trumpet', 'Case', 'Mouthpiece'],
    sku: 'BACH-STRAV-37',
    rating: 4.9,
    reviewCount: 312,
  },
  {
    id: '11',
    name: 'Yamaha YTR-8335G Xeno Trumpet',
    slug: 'yamaha-ytr-8335g-xeno-trumpet',
    brand: 'Yamaha',
    price: 2999.00,
    category: 'brasswinds',
    subcategory: 'trumpets',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+Xeno'],
    badge: 'new',
    inStock: true,
    stock: 4,
    description: 'Professional trumpet with gold brass bell. Exceptional projection and tone.',
    specs: {
      'Key': 'Bb',
      'Bell': '4-7/8"',
      'Bore': 'ML',
    },
    included: ['Yamaha Xeno Trumpet', 'Case'],
    sku: 'YTR-8335G',
    rating: 4.8,
    reviewCount: 189,
  },
  {
    id: '12',
    name: 'Yamaha YTR-2330 Student Trumpet',
    slug: 'yamaha-ytr-2330-student-trumpet',
    brand: 'Yamaha',
    price: 899.00,
    retailPrice: 1099.00,
    category: 'brasswinds',
    subcategory: 'trumpets',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YTR-2330'],
    badge: 'sale',
    inStock: true,
    stock: 12,
    description: 'Perfect starter trumpet for students. Durable construction and excellent intonation.',
    specs: {
      'Key': 'Bb',
      'Bell': '4-7/8"',
    },
    included: ['Yamaha YTR-2330 Trumpet', 'Case', 'Mouthpiece'],
    sku: 'YTR-2330',
    rating: 4.5,
    reviewCount: 278,
  },
  // Trombones
  {
    id: '13',
    name: 'Yamaha YSL-882O Xeno Trombone',
    slug: 'yamaha-ysl-882o-xeno-trombone',
    brand: 'Yamaha',
    price: 3499.00,
    category: 'brasswinds',
    subcategory: 'trombones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+Xeno+Trombone'],
    badge: 'new',
    inStock: true,
    stock: 3,
    description: 'Professional trombone with F-attachment. Rich, warm tone with excellent projection.',
    specs: {
      'Key': 'Bb',
      'Bore': '0.547"',
      'Bell': '8-1/2"',
    },
    included: ['Yamaha Xeno Trombone', 'Case'],
    sku: 'YSL-882O',
    rating: 4.9,
    reviewCount: 56,
  },
  {
    id: '14',
    name: 'Bach 42BO Stradivarius Trombone',
    slug: 'bach-42bo-stradivarius-trombone',
    brand: 'Bach',
    price: 3999.00,
    category: 'brasswinds',
    subcategory: 'trombones',
    images: ['https://via.placeholder.com/800x800?text=Bach+42BO'],
    inStock: true,
    stock: 2,
    description: 'Professional trombone with open wrap F-attachment. Industry standard.',
    specs: {
      'Key': 'Bb',
      'Bore': '0.547"',
      'Bell': '8-1/2"',
    },
    included: ['Bach 42BO Trombone', 'Case'],
    sku: 'BACH-42BO',
    rating: 4.8,
    reviewCount: 134,
  },
  // French Horns
  {
    id: '15',
    name: 'Yamaha YHR-567D French Horn',
    slug: 'yamaha-yhr-567d-french-horn',
    brand: 'Yamaha',
    price: 4499.00,
    category: 'brasswinds',
    subcategory: 'french-horns',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+French+Horn'],
    badge: 'new',
    inStock: true,
    stock: 2,
    description: 'Professional double French horn. Excellent intonation and response.',
    specs: {
      'Key': 'F/Bb',
      'Bell': '12"',
    },
    included: ['Yamaha French Horn', 'Case'],
    sku: 'YHR-567D',
    rating: 4.7,
    reviewCount: 34,
  },
  // Mouthpieces & Accessories
  {
    id: '16',
    name: 'Vandoren AL3 Alto Saxophone Mouthpiece',
    slug: 'vandoren-al3-alto-saxophone-mouthpiece',
    brand: 'Vandoren',
    price: 149.00,
    category: 'woodwinds',
    subcategory: 'mouthpieces-ligs',
    images: ['https://via.placeholder.com/800x800?text=Vandoren+AL3'],
    inStock: true,
    stock: 15,
    description: 'Professional alto saxophone mouthpiece. Rich, warm tone with excellent projection.',
    specs: {
      'Tip Opening': 'Medium',
      'Facing': 'Medium',
    },
    included: ['Vandoren AL3 Mouthpiece'],
    sku: 'VAN-AL3',
    rating: 4.6,
    reviewCount: 89,
  },
  {
    id: '17',
    name: 'Rico Royal Alto Saxophone Reeds (Box of 10)',
    slug: 'rico-royal-alto-saxophone-reeds',
    brand: 'Rico',
    price: 24.99,
    category: 'woodwinds',
    subcategory: 'accessories',
    images: ['https://via.placeholder.com/800x800?text=Rico+Royal+Reeds'],
    inStock: true,
    stock: 50,
    description: 'High-quality cane reeds for alto saxophone. Consistent response and tone.',
    specs: {
      'Strength': '2.5',
      'Quantity': '10 reeds',
    },
    included: ['Box of 10 Reeds'],
    sku: 'RICO-ALTO-25',
    rating: 4.5,
    reviewCount: 234,
  },
  {
    id: '18',
    name: 'Vandoren Optimum Ligature for Alto Sax',
    slug: 'vandoren-optimum-ligature-alto-sax',
    brand: 'Vandoren',
    price: 89.00,
    category: 'woodwinds',
    subcategory: 'mouthpieces-ligs',
    images: ['https://via.placeholder.com/800x800?text=Vandoren+Ligature'],
    inStock: true,
    stock: 20,
    description: 'Professional ligature for enhanced tone and response.',
    specs: {
      'Material': 'Metal',
      'Size': 'Alto Sax',
    },
    included: ['Vandoren Optimum Ligature'],
    sku: 'VAN-OPT-ALTO',
    rating: 4.7,
    reviewCount: 67,
  },
  {
    id: '19',
    name: 'BAM High-Tech Alto Saxophone Case',
    slug: 'bam-high-tech-alto-saxophone-case',
    brand: 'BAM',
    price: 399.00,
    category: 'woodwinds',
    subcategory: 'accessories',
    images: ['https://via.placeholder.com/800x800?text=BAM+Case'],
    badge: 'new',
    inStock: true,
    stock: 8,
    description: 'Lightweight, durable case with excellent protection. Fits most alto saxophones.',
    specs: {
      'Material': 'Carbon Fiber',
      'Weight': '2.5 kg',
    },
    included: ['BAM Case'],
    sku: 'BAM-ALTO-HT',
    rating: 4.8,
    reviewCount: 45,
  },
  {
    id: '20',
    name: 'Selmer S80 C* Clarinet Mouthpiece',
    slug: 'selmer-s80-c-clarinet-mouthpiece',
    brand: 'Selmer',
    price: 129.00,
    category: 'woodwinds',
    subcategory: 'mouthpieces-ligs',
    images: ['https://via.placeholder.com/800x800?text=Selmer+S80'],
    inStock: true,
    stock: 12,
    description: 'Professional clarinet mouthpiece. Industry standard for classical playing.',
    specs: {
      'Tip Opening': 'C*',
    },
    included: ['Selmer S80 Mouthpiece'],
    sku: 'SEL-S80-C',
    rating: 4.9,
    reviewCount: 156,
  },
  // More products to reach 40+
  {
    id: '21',
    name: 'Yamaha YAS-62 Alto Saxophone',
    slug: 'yamaha-yas-62-alto-saxophone',
    brand: 'Yamaha',
    price: 2499.00,
    retailPrice: 2999.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YAS-62'],
    badge: 'sale',
    inStock: true,
    stock: 6,
    description: 'Professional alto saxophone with excellent tone and response.',
    sku: 'YAS-62',
    rating: 4.7,
    reviewCount: 198,
  },
  {
    id: '22',
    name: 'Yamaha YTS-62 Tenor Saxophone',
    slug: 'yamaha-yts-62-tenor-saxophone',
    brand: 'Yamaha',
    price: 2799.00,
    retailPrice: 3299.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YTS-62'],
    badge: 'sale',
    inStock: true,
    stock: 4,
    description: 'Professional tenor saxophone with rich, warm tone.',
    sku: 'YTS-62',
    rating: 4.8,
    reviewCount: 167,
  },
  {
    id: '23',
    name: 'Yamaha YBS-62 Baritone Saxophone',
    slug: 'yamaha-ybs-62-baritone-saxophone',
    brand: 'Yamaha',
    price: 5999.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YBS-62'],
    badge: 'limited',
    inStock: true,
    stock: 1,
    description: 'Professional baritone saxophone. Powerful, rich tone.',
    sku: 'YBS-62',
    rating: 4.9,
    reviewCount: 23,
  },
  {
    id: '24',
    name: 'Yamaha YSS-475 Soprano Saxophone',
    slug: 'yamaha-yss-475-soprano-saxophone',
    brand: 'Yamaha',
    price: 2299.00,
    category: 'woodwinds',
    subcategory: 'saxophones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YSS-475'],
    inStock: true,
    stock: 3,
    description: 'Professional soprano saxophone with excellent intonation.',
    sku: 'YSS-475',
    rating: 4.6,
    reviewCount: 45,
  },
  {
    id: '25',
    name: 'Buffet Crampon E13 Bb Clarinet',
    slug: 'buffet-crampon-e13-bb-clarinet',
    brand: 'Buffet Crampon',
    price: 2299.00,
    category: 'woodwinds',
    subcategory: 'clarinets',
    images: ['https://via.placeholder.com/800x800?text=Buffet+E13'],
    inStock: true,
    stock: 5,
    description: 'Intermediate clarinet with professional features.',
    sku: 'E13-BB',
    rating: 4.5,
    reviewCount: 78,
  },
  {
    id: '26',
    name: 'Yamaha YCL-255 Student Clarinet',
    slug: 'yamaha-ycl-255-student-clarinet',
    brand: 'Yamaha',
    price: 699.00,
    retailPrice: 899.00,
    category: 'woodwinds',
    subcategory: 'clarinets',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YCL-255'],
    badge: 'sale',
    inStock: true,
    stock: 15,
    description: 'Perfect starter clarinet for students.',
    sku: 'YCL-255',
    rating: 4.4,
    reviewCount: 312,
  },
  {
    id: '27',
    name: 'Yamaha YFL-221 Student Flute',
    slug: 'yamaha-yfl-221-student-flute',
    brand: 'Yamaha',
    price: 599.00,
    retailPrice: 799.00,
    category: 'woodwinds',
    subcategory: 'flutes',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YFL-221'],
    badge: 'sale',
    inStock: true,
    stock: 20,
    description: 'Excellent student flute with durable construction.',
    sku: 'YFL-221',
    rating: 4.5,
    reviewCount: 456,
  },
  {
    id: '28',
    name: 'Yamaha YFL-677 Professional Flute',
    slug: 'yamaha-yfl-677-professional-flute',
    brand: 'Yamaha',
    price: 3999.00,
    category: 'woodwinds',
    subcategory: 'flutes',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YFL-677'],
    badge: 'new',
    inStock: true,
    stock: 4,
    description: 'Professional flute with silver headjoint.',
    sku: 'YFL-677',
    rating: 4.8,
    reviewCount: 89,
  },
  {
    id: '29',
    name: 'Bach 180S37 Stradivarius Bb Trumpet',
    slug: 'bach-180s37-stradivarius-bb-trumpet',
    brand: 'Bach',
    price: 3299.00,
    retailPrice: 3799.00,
    category: 'brasswinds',
    subcategory: 'trumpets',
    images: ['https://via.placeholder.com/800x800?text=Bach+180S37'],
    badge: 'sale',
    inStock: true,
    stock: 5,
    description: 'Professional trumpet with excellent projection.',
    sku: 'BACH-180S37',
    rating: 4.9,
    reviewCount: 234,
  },
  {
    id: '30',
    name: 'Yamaha YTR-8310Z Xeno Trumpet',
    slug: 'yamaha-ytr-8310z-xeno-trumpet',
    brand: 'Yamaha',
    price: 2799.00,
    category: 'brasswinds',
    subcategory: 'trumpets',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YTR-8310Z'],
    inStock: true,
    stock: 6,
    description: 'Professional trumpet with gold brass bell.',
    sku: 'YTR-8310Z',
    rating: 4.7,
    reviewCount: 123,
  },
  {
    id: '31',
    name: 'Yamaha YSL-354 Student Trombone',
    slug: 'yamaha-ysl-354-student-trombone',
    brand: 'Yamaha',
    price: 799.00,
    retailPrice: 999.00,
    category: 'brasswinds',
    subcategory: 'trombones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YSL-354'],
    badge: 'sale',
    inStock: true,
    stock: 10,
    description: 'Perfect starter trombone for students.',
    sku: 'YSL-354',
    rating: 4.4,
    reviewCount: 267,
  },
  {
    id: '32',
    name: 'Yamaha YSL-882G Xeno Trombone',
    slug: 'yamaha-ysl-882g-xeno-trombone',
    brand: 'Yamaha',
    price: 3299.00,
    category: 'brasswinds',
    subcategory: 'trombones',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YSL-882G'],
    badge: 'new',
    inStock: true,
    stock: 3,
    description: 'Professional trombone with F-attachment.',
    sku: 'YSL-882G',
    rating: 4.8,
    reviewCount: 67,
  },
  {
    id: '33',
    name: 'Yamaha YHR-567 French Horn',
    slug: 'yamaha-yhr-567-french-horn',
    brand: 'Yamaha',
    price: 3999.00,
    category: 'brasswinds',
    subcategory: 'french-horns',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YHR-567'],
    inStock: true,
    stock: 2,
    description: 'Professional double French horn.',
    sku: 'YHR-567',
    rating: 4.7,
    reviewCount: 34,
  },
  {
    id: '34',
    name: 'Yamaha YEP-642S Euphonium',
    slug: 'yamaha-yep-642s-euphonium',
    brand: 'Yamaha',
    price: 3499.00,
    category: 'brasswinds',
    subcategory: 'euphoniums',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YEP-642S'],
    badge: 'new',
    inStock: true,
    stock: 2,
    description: 'Professional euphonium with 4 valves.',
    sku: 'YEP-642S',
    rating: 4.6,
    reviewCount: 23,
  },
  {
    id: '35',
    name: 'Yamaha YFH-631G Flugel Horn',
    slug: 'yamaha-yfh-631g-flugel-horn',
    brand: 'Yamaha',
    price: 2499.00,
    category: 'brasswinds',
    subcategory: 'flugel-horns',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+YFH-631G'],
    inStock: true,
    stock: 3,
    description: 'Professional flugel horn with gold brass bell.',
    sku: 'YFH-631G',
    rating: 4.5,
    reviewCount: 45,
  },
  {
    id: '36',
    name: 'Yamaha YSH-301 Silent Brass System',
    slug: 'yamaha-ysh-301-silent-brass-system',
    brand: 'Yamaha',
    price: 299.00,
    category: 'brasswinds',
    subcategory: 'yamaha-silent-brass',
    images: ['https://via.placeholder.com/800x800?text=Yamaha+Silent+Brass'],
    inStock: true,
    stock: 12,
    description: 'Practice silently with headphones. Works with all brass instruments.',
    sku: 'YSH-301',
    rating: 4.6,
    reviewCount: 178,
  },
  {
    id: '37',
    name: 'Vandoren TL3 Tenor Saxophone Mouthpiece',
    slug: 'vandoren-tl3-tenor-saxophone-mouthpiece',
    brand: 'Vandoren',
    price: 159.00,
    category: 'woodwinds',
    subcategory: 'mouthpieces-ligs',
    images: ['https://via.placeholder.com/800x800?text=Vandoren+TL3'],
    inStock: true,
    stock: 18,
    description: 'Professional tenor saxophone mouthpiece.',
    sku: 'VAN-TL3',
    rating: 4.7,
    reviewCount: 92,
  },
  {
    id: '38',
    name: 'Rico Royal Tenor Saxophone Reeds (Box of 10)',
    slug: 'rico-royal-tenor-saxophone-reeds',
    brand: 'Rico',
    price: 26.99,
    category: 'woodwinds',
    subcategory: 'accessories',
    images: ['https://via.placeholder.com/800x800?text=Rico+Tenor+Reeds'],
    inStock: true,
    stock: 45,
    description: 'High-quality cane reeds for tenor saxophone.',
    sku: 'RICO-TENOR-25',
    rating: 4.5,
    reviewCount: 189,
  },
  {
    id: '39',
    name: 'BAM High-Tech Tenor Saxophone Case',
    slug: 'bam-high-tech-tenor-saxophone-case',
    brand: 'BAM',
    price: 449.00,
    category: 'woodwinds',
    subcategory: 'accessories',
    images: ['https://via.placeholder.com/800x800?text=BAM+Tenor+Case'],
    badge: 'new',
    inStock: true,
    stock: 6,
    description: 'Lightweight, durable case for tenor saxophone.',
    sku: 'BAM-TENOR-HT',
    rating: 4.8,
    reviewCount: 34,
  },
  {
    id: '40',
    name: 'Vandoren B45 Clarinet Mouthpiece',
    slug: 'vandoren-b45-clarinet-mouthpiece',
    brand: 'Vandoren',
    price: 119.00,
    category: 'woodwinds',
    subcategory: 'mouthpieces-ligs',
    images: ['https://via.placeholder.com/800x800?text=Vandoren+B45'],
    inStock: true,
    stock: 22,
    description: 'Professional clarinet mouthpiece. Great for jazz and classical.',
    sku: 'VAN-B45',
    rating: 4.6,
    reviewCount: 145,
  },
]

// Promo Banners
export const promoBanners: PromoBanner[] = [
  {
    id: '1',
    title: 'Special Financing Available',
    description: '0% APR for 12 months on qualifying purchases over $500. Make your dream instrument affordable with flexible payment options.',
    image: 'https://via.placeholder.com/1200x400?text=Financing+Promo',
    validUntil: 'December 31, 2024',
    ctaText: 'Learn More',
    ctaLink: '/financing',
  },
  {
    id: '2',
    title: 'New Arrivals: Professional Saxophones',
    description: 'Just in: Latest models from Yamaha, Selmer, and Yanagisawa. Each instrument professionally set up and ready to play.',
    image: 'https://via.placeholder.com/1200x400?text=New+Arrivals',
    validUntil: 'While supplies last',
    ctaText: 'Shop Now',
    ctaLink: '/shop/woodwinds/saxophones',
  },
  {
    id: '3',
    title: 'Professional Setup Included',
    description: 'Every instrument purchased includes our expert setup service—valued at $150. We ensure optimal playability before shipping.',
    image: 'https://via.placeholder.com/1200x400?text=Professional+Setup',
    validUntil: 'Always included',
    ctaText: 'Learn More',
    ctaLink: '/professional-setup',
  },
  {
    id: '4',
    title: 'School Music Rentals Available',
    description: 'Rent quality instruments for your students with flexible terms. Free delivery to schools. Perfect for band programs.',
    image: 'https://via.placeholder.com/1200x400?text=School+Rentals',
    validUntil: 'Year-round program',
    ctaText: 'View Rental Options',
    ctaLink: '/rentals',
  },
  {
    id: '5',
    title: 'End of Season Sale',
    description: 'Save up to 30% on select student and intermediate instruments. Limited time offer on overstocked items.',
    image: 'https://via.placeholder.com/1200x400?text=Sale',
    validUntil: 'December 31, 2024',
    ctaText: 'Shop Sale Items',
    ctaLink: '/shop?filter=sale',
  },
  {
    id: '6',
    title: 'Need Help Choosing?',
    description: 'Our specialists are here to help. Call, email, or visit our showroom for personalized recommendations.',
    image: 'https://via.placeholder.com/1200x400?text=Expert+Advice',
    validUntil: 'Always available',
    ctaText: 'Contact an Expert',
    ctaLink: '/contact',
  },
  {
    id: '7',
    title: 'Free Shipping on Orders Over $500',
    description: 'Most items ship within 2-3 business days with tracking included. Professional setup still included.',
    image: 'https://via.placeholder.com/1200x400?text=Free+Shipping',
    validUntil: 'Ongoing',
    ctaText: 'Shop Now',
    ctaLink: '/shop',
  },
  {
    id: '8',
    title: 'Holiday Special: 15% Off Accessories',
    description: 'Save on reeds, mouthpieces, ligatures, and cases. Perfect time to stock up on essentials.',
    image: 'https://via.placeholder.com/1200x400?text=Holiday+Special',
    validUntil: 'December 25, 2024',
    ctaText: 'Shop Accessories',
    ctaLink: '/shop/woodwinds/accessories',
  },
]

// Featured Collections
export const featuredCollections: FeaturedCollection[] = [
  {
    id: '1',
    name: 'Professional Saxophones',
    slug: 'professional-saxophones',
    productIds: ['2', '5', '21', '22'],
  },
  {
    id: '2',
    name: 'Student Instruments',
    slug: 'student-instruments',
    productIds: ['1', '4', '12', '26', '27', '31'],
  },
  {
    id: '3',
    name: 'On Sale',
    slug: 'on-sale',
    productIds: ['1', '4', '6', '10', '12', '21', '22', '26', '27', '29', '31'],
  },
  {
    id: '4',
    name: 'New Arrivals',
    slug: 'new-arrivals',
    productIds: ['2', '8', '11', '13', '15', '19', '28', '32', '34', '39'],
  },
  {
    id: '5',
    name: 'Accessories',
    slug: 'accessories',
    productIds: ['16', '17', '18', '19', '20', '36', '37', '38', '39', '40'],
  },
  {
    id: '6',
    name: 'Professional Brass',
    slug: 'professional-brass',
    productIds: ['10', '11', '13', '14', '15', '29', '30', '32', '33', '34'],
  },
]

// Helper functions
export function getProductBySlug(slug: string): Product | undefined {
  return products.find(p => p.slug === slug)
}

export function getProductsByCategory(category: string, subcategory?: string): Product[] {
  return products.filter(p => {
    if (subcategory) {
      return p.category === category && p.subcategory === subcategory
    }
    return p.category === category
  })
}

export function getFeaturedProducts(collectionId: string): Product[] {
  const collection = featuredCollections.find(c => c.id === collectionId)
  if (!collection) return []
  return products.filter(p => collection.productIds.includes(p.id))
}

