// Location data for Country, State/Province, City dropdowns

export interface Country {
  name: string
  code: string
  states: State[]
}

export interface State {
  name: string
  code: string
  cities?: string[]
}

export const countries: Country[] = [
  // United States first (priority)
  {
    name: 'United States',
    code: 'US',
    states: [
      { name: 'Alabama', code: 'AL' },
      { name: 'Alaska', code: 'AK' },
      { name: 'Arizona', code: 'AZ' },
      { name: 'Arkansas', code: 'AR' },
      { name: 'California', code: 'CA' },
      { name: 'Colorado', code: 'CO' },
      { name: 'Connecticut', code: 'CT' },
      { name: 'Delaware', code: 'DE' },
      { name: 'Florida', code: 'FL' },
      { name: 'Georgia', code: 'GA' },
      { name: 'Hawaii', code: 'HI' },
      { name: 'Idaho', code: 'ID' },
      { name: 'Illinois', code: 'IL' },
      { name: 'Indiana', code: 'IN' },
      { name: 'Iowa', code: 'IA' },
      { name: 'Kansas', code: 'KS' },
      { name: 'Kentucky', code: 'KY' },
      { name: 'Louisiana', code: 'LA' },
      { name: 'Maine', code: 'ME' },
      { name: 'Maryland', code: 'MD' },
      { name: 'Massachusetts', code: 'MA' },
      { name: 'Michigan', code: 'MI' },
      { name: 'Minnesota', code: 'MN' },
      { name: 'Mississippi', code: 'MS' },
      { name: 'Missouri', code: 'MO' },
      { name: 'Montana', code: 'MT' },
      { name: 'Nebraska', code: 'NE' },
      { name: 'Nevada', code: 'NV' },
      { name: 'New Hampshire', code: 'NH' },
      { name: 'New Jersey', code: 'NJ' },
      { name: 'New Mexico', code: 'NM' },
      { name: 'New York', code: 'NY' },
      { name: 'North Carolina', code: 'NC' },
      { name: 'North Dakota', code: 'ND' },
      { name: 'Ohio', code: 'OH' },
      { name: 'Oklahoma', code: 'OK' },
      { name: 'Oregon', code: 'OR' },
      { name: 'Pennsylvania', code: 'PA' },
      { name: 'Rhode Island', code: 'RI' },
      { name: 'South Carolina', code: 'SC' },
      { name: 'South Dakota', code: 'SD' },
      { name: 'Tennessee', code: 'TN' },
      { name: 'Texas', code: 'TX' },
      { name: 'Utah', code: 'UT' },
      { name: 'Vermont', code: 'VT' },
      { name: 'Virginia', code: 'VA' },
      { name: 'Washington', code: 'WA' },
      { name: 'West Virginia', code: 'WV' },
      { name: 'Wisconsin', code: 'WI' },
      { name: 'Wyoming', code: 'WY' },
      { name: 'District of Columbia', code: 'DC' },
    ]
  },
  // Rest alphabetically sorted (A-Z)
  {
    name: 'Australia',
    code: 'AU',
    states: [
      { name: 'Australian Capital Territory', code: 'ACT' },
      { name: 'New South Wales', code: 'NSW' },
      { name: 'Northern Territory', code: 'NT' },
      { name: 'Queensland', code: 'QLD' },
      { name: 'South Australia', code: 'SA' },
      { name: 'Tasmania', code: 'TAS' },
      { name: 'Victoria', code: 'VIC' },
      { name: 'Western Australia', code: 'WA' },
    ]
  },
  { name: 'Belgium', code: 'BE', states: [] },
  { name: 'Brazil', code: 'BR', states: [] },
  {
    name: 'Canada',
    code: 'CA',
    states: [
      { name: 'Alberta', code: 'AB' },
      { name: 'British Columbia', code: 'BC' },
      { name: 'Manitoba', code: 'MB' },
      { name: 'New Brunswick', code: 'NB' },
      { name: 'Newfoundland and Labrador', code: 'NL' },
      { name: 'Northwest Territories', code: 'NT' },
      { name: 'Nova Scotia', code: 'NS' },
      { name: 'Nunavut', code: 'NU' },
      { name: 'Ontario', code: 'ON' },
      { name: 'Prince Edward Island', code: 'PE' },
      { name: 'Quebec', code: 'QC' },
      { name: 'Saskatchewan', code: 'SK' },
      { name: 'Yukon', code: 'YT' },
    ]
  },
  { name: 'China', code: 'CN', states: [
    { name: 'Beijing', code: 'BJ' },
    { name: 'Shanghai', code: 'SH' },
    { name: 'Guangdong', code: 'GD' },
    { name: 'Zhejiang', code: 'ZJ' },
    { name: 'Jiangsu', code: 'JS' },
  ]},
  { name: 'Denmark', code: 'DK', states: [] },
  {
    name: 'France',
    code: 'FR',
    states: [
      { name: 'Auvergne-Rhône-Alpes', code: 'ARA' },
      { name: 'Bourgogne-Franche-Comté', code: 'BFC' },
      { name: 'Brittany', code: 'BRE' },
      { name: 'Centre-Val de Loire', code: 'CVL' },
      { name: 'Corsica', code: 'COR' },
      { name: 'Grand Est', code: 'GES' },
      { name: 'Hauts-de-France', code: 'HDF' },
      { name: 'Île-de-France', code: 'IDF' },
      { name: 'Normandy', code: 'NOR' },
      { name: 'Nouvelle-Aquitaine', code: 'NAQ' },
      { name: 'Occitanie', code: 'OCC' },
      { name: 'Pays de la Loire', code: 'PDL' },
      { name: "Provence-Alpes-Côte d'Azur", code: 'PAC' },
    ]
  },
  {
    name: 'Germany',
    code: 'DE',
    states: [
      { name: 'Baden-Württemberg', code: 'BW' },
      { name: 'Bavaria', code: 'BY' },
      { name: 'Berlin', code: 'BE' },
      { name: 'Brandenburg', code: 'BB' },
      { name: 'Bremen', code: 'HB' },
      { name: 'Hamburg', code: 'HH' },
      { name: 'Hesse', code: 'HE' },
      { name: 'Lower Saxony', code: 'NI' },
      { name: 'Mecklenburg-Vorpommern', code: 'MV' },
      { name: 'North Rhine-Westphalia', code: 'NW' },
      { name: 'Rhineland-Palatinate', code: 'RP' },
      { name: 'Saarland', code: 'SL' },
      { name: 'Saxony', code: 'SN' },
      { name: 'Saxony-Anhalt', code: 'ST' },
      { name: 'Schleswig-Holstein', code: 'SH' },
      { name: 'Thuringia', code: 'TH' },
    ]
  },
  { name: 'Hong Kong', code: 'HK', states: [] },
  { name: 'India', code: 'IN', states: [
    { name: 'Andhra Pradesh', code: 'AP' },
    { name: 'Delhi', code: 'DL' },
    { name: 'Gujarat', code: 'GJ' },
    { name: 'Karnataka', code: 'KA' },
    { name: 'Maharashtra', code: 'MH' },
    { name: 'Tamil Nadu', code: 'TN' },
    { name: 'West Bengal', code: 'WB' },
  ]},
  { name: 'Indonesia', code: 'ID', states: [
    { name: 'Jakarta', code: 'JK' },
    { name: 'West Java', code: 'JB' },
    { name: 'Central Java', code: 'JT' },
    { name: 'East Java', code: 'JI' },
    { name: 'Bali', code: 'BA' },
  ]},
  { name: 'Italy', code: 'IT', states: [] },
  {
    name: 'Japan',
    code: 'JP',
    states: [
      { name: 'Hokkaido', code: 'HK' },
      { name: 'Aomori', code: 'AO' },
      { name: 'Iwate', code: 'IW' },
      { name: 'Miyagi', code: 'MY' },
      { name: 'Akita', code: 'AK' },
      { name: 'Yamagata', code: 'YA' },
      { name: 'Fukushima', code: 'FS' },
      { name: 'Ibaraki', code: 'IB' },
      { name: 'Tochigi', code: 'TC' },
      { name: 'Gunma', code: 'GU' },
      { name: 'Saitama', code: 'SA' },
      { name: 'Chiba', code: 'CB' },
      { name: 'Tokyo', code: 'TK' },
      { name: 'Kanagawa', code: 'KN' },
      { name: 'Niigata', code: 'NI' },
      { name: 'Toyama', code: 'TY' },
      { name: 'Ishikawa', code: 'IS' },
      { name: 'Fukui', code: 'FI' },
      { name: 'Yamanashi', code: 'YN' },
      { name: 'Nagano', code: 'NG' },
      { name: 'Gifu', code: 'GF' },
      { name: 'Shizuoka', code: 'SZ' },
      { name: 'Aichi', code: 'AI' },
      { name: 'Mie', code: 'ME' },
      { name: 'Shiga', code: 'SG' },
      { name: 'Kyoto', code: 'KY' },
      { name: 'Osaka', code: 'OS' },
      { name: 'Hyogo', code: 'HY' },
      { name: 'Nara', code: 'NR' },
      { name: 'Wakayama', code: 'WK' },
      { name: 'Tottori', code: 'TT' },
      { name: 'Shimane', code: 'SM' },
      { name: 'Okayama', code: 'OK' },
      { name: 'Hiroshima', code: 'HR' },
      { name: 'Yamaguchi', code: 'YG' },
      { name: 'Tokushima', code: 'TS' },
      { name: 'Kagawa', code: 'KG' },
      { name: 'Ehime', code: 'EH' },
      { name: 'Kochi', code: 'KC' },
      { name: 'Fukuoka', code: 'FO' },
      { name: 'Saga', code: 'SGA' },
      { name: 'Nagasaki', code: 'NS' },
      { name: 'Kumamoto', code: 'KM' },
      { name: 'Oita', code: 'OI' },
      { name: 'Miyazaki', code: 'MZ' },
      { name: 'Kagoshima', code: 'KS' },
      { name: 'Okinawa', code: 'ON' },
    ]
  },
  { name: 'Malaysia', code: 'MY', states: [
    { name: 'Johor', code: 'JH' },
    { name: 'Kedah', code: 'KD' },
    { name: 'Kelantan', code: 'KN' },
    { name: 'Kuala Lumpur', code: 'KL' },
    { name: 'Labuan', code: 'LB' },
    { name: 'Melaka', code: 'ML' },
    { name: 'Negeri Sembilan', code: 'NS' },
    { name: 'Pahang', code: 'PH' },
    { name: 'Penang', code: 'PN' },
    { name: 'Perak', code: 'PK' },
    { name: 'Perlis', code: 'PL' },
    { name: 'Putrajaya', code: 'PJ' },
    { name: 'Sabah', code: 'SB' },
    { name: 'Sarawak', code: 'SR' },
    { name: 'Selangor', code: 'SL' },
    { name: 'Terengganu', code: 'TR' },
  ]},
  { name: 'Mexico', code: 'MX', states: [] },
  { name: 'Netherlands', code: 'NL', states: [] },
  { name: 'New Zealand', code: 'NZ', states: [] },
  { name: 'Norway', code: 'NO', states: [] },
  { name: 'Philippines', code: 'PH', states: [
    { name: 'Metro Manila', code: 'NCR' },
    { name: 'Cebu', code: 'CEB' },
    { name: 'Davao', code: 'DAV' },
  ]},
  { name: 'Singapore', code: 'SG', states: [] },
  { name: 'South Korea', code: 'KR', states: [
    { name: 'Seoul', code: 'SE' },
    { name: 'Busan', code: 'BS' },
    { name: 'Daegu', code: 'DG' },
    { name: 'Incheon', code: 'IC' },
    { name: 'Gwangju', code: 'GJ' },
    { name: 'Daejeon', code: 'DJ' },
    { name: 'Ulsan', code: 'US' },
    { name: 'Sejong', code: 'SJ' },
    { name: 'Gyeonggi', code: 'GG' },
    { name: 'Gangwon', code: 'GW' },
    { name: 'North Chungcheong', code: 'CB' },
    { name: 'South Chungcheong', code: 'CN' },
    { name: 'North Jeolla', code: 'JB' },
    { name: 'South Jeolla', code: 'JN' },
    { name: 'North Gyeongsang', code: 'GB' },
    { name: 'South Gyeongsang', code: 'GN' },
    { name: 'Jeju', code: 'JJ' },
  ]},
  { name: 'Spain', code: 'ES', states: [] },
  { name: 'Sweden', code: 'SE', states: [] },
  { name: 'Switzerland', code: 'CH', states: [] },
  { name: 'Taiwan', code: 'TW', states: [
    { name: 'Taipei', code: 'TP' },
    { name: 'New Taipei', code: 'NT' },
    { name: 'Taichung', code: 'TC' },
    { name: 'Kaohsiung', code: 'KH' },
    { name: 'Tainan', code: 'TN' },
  ]},
  { name: 'Thailand', code: 'TH', states: [
    { name: 'Bangkok', code: 'BKK' },
    { name: 'Chiang Mai', code: 'CM' },
    { name: 'Phuket', code: 'PK' },
    { name: 'Chonburi', code: 'CB' },
    { name: 'Nonthaburi', code: 'NB' },
  ]},
  {
    name: 'United Kingdom',
    code: 'GB',
    states: [
      { name: 'England', code: 'ENG' },
      { name: 'Scotland', code: 'SCT' },
      { name: 'Wales', code: 'WLS' },
      { name: 'Northern Ireland', code: 'NIR' },
    ]
  },
  {
    name: 'Vietnam',
    code: 'VN',
    states: [
      { name: 'An Giang', code: 'AG' },
      { name: 'Bà Rịa - Vũng Tàu', code: 'BR' },
      { name: 'Bắc Giang', code: 'BG' },
      { name: 'Bắc Kạn', code: 'BK' },
      { name: 'Bạc Liêu', code: 'BL' },
      { name: 'Bắc Ninh', code: 'BN' },
      { name: 'Bến Tre', code: 'BT' },
      { name: 'Bình Định', code: 'BD' },
      { name: 'Bình Dương', code: 'BI' },
      { name: 'Bình Phước', code: 'BP' },
      { name: 'Bình Thuận', code: 'BTH' },
      { name: 'Cà Mau', code: 'CM' },
      { name: 'Cần Thơ', code: 'CT' },
      { name: 'Cao Bằng', code: 'CB' },
      { name: 'Đà Nẵng', code: 'DN' },
      { name: 'Đắk Lắk', code: 'DL' },
      { name: 'Đắk Nông', code: 'DNo' },
      { name: 'Điện Biên', code: 'DB' },
      { name: 'Đồng Nai', code: 'DNa' },
      { name: 'Đồng Tháp', code: 'DT' },
      { name: 'Gia Lai', code: 'GL' },
      { name: 'Hà Giang', code: 'HG' },
      { name: 'Hà Nam', code: 'HNa' },
      { name: 'Hà Nội', code: 'HN' },
      { name: 'Hà Tĩnh', code: 'HT' },
      { name: 'Hải Dương', code: 'HD' },
      { name: 'Hải Phòng', code: 'HP' },
      { name: 'Hậu Giang', code: 'HGi' },
      { name: 'Hòa Bình', code: 'HB' },
      { name: 'Hồ Chí Minh', code: 'HCM' },
      { name: 'Hưng Yên', code: 'HY' },
      { name: 'Khánh Hòa', code: 'KH' },
      { name: 'Kiên Giang', code: 'KG' },
      { name: 'Kon Tum', code: 'KT' },
      { name: 'Lai Châu', code: 'LC' },
      { name: 'Lâm Đồng', code: 'LD' },
      { name: 'Lạng Sơn', code: 'LS' },
      { name: 'Lào Cai', code: 'LCa' },
      { name: 'Long An', code: 'LA' },
      { name: 'Nam Định', code: 'ND' },
      { name: 'Nghệ An', code: 'NA' },
      { name: 'Ninh Bình', code: 'NB' },
      { name: 'Ninh Thuận', code: 'NT' },
      { name: 'Phú Thọ', code: 'PT' },
      { name: 'Phú Yên', code: 'PY' },
      { name: 'Quảng Bình', code: 'QB' },
      { name: 'Quảng Nam', code: 'QNa' },
      { name: 'Quảng Ngãi', code: 'QNg' },
      { name: 'Quảng Ninh', code: 'QN' },
      { name: 'Quảng Trị', code: 'QT' },
      { name: 'Sóc Trăng', code: 'ST' },
      { name: 'Sơn La', code: 'SL' },
      { name: 'Tây Ninh', code: 'TN' },
      { name: 'Thái Bình', code: 'TB' },
      { name: 'Thái Nguyên', code: 'TNG' },
      { name: 'Thanh Hóa', code: 'TH' },
      { name: 'Thừa Thiên Huế', code: 'TTH' },
      { name: 'Tiền Giang', code: 'TG' },
      { name: 'Trà Vinh', code: 'TV' },
      { name: 'Tuyên Quang', code: 'TQ' },
      { name: 'Vĩnh Long', code: 'VL' },
      { name: 'Vĩnh Phúc', code: 'VP' },
      { name: 'Yên Bái', code: 'YB' },
    ]
  },
]

export function getCountryByName(name: string): Country | undefined {
  return countries.find(c => c.name === name)
}

export function getStatesByCountry(countryName: string): State[] {
  const country = getCountryByName(countryName)
  return country?.states || []
}
